{application,ePaxos,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{ePaxos_app,[]}},
              {env,[]},
              {modules,[ePaxosServer,ePaxos_app,ePaxos_server,ePaxos_sup,
                        paxos_acceptor,paxos_proposer]}]}.
